set -gq @thm_background "#181616"
set -gq @thm_foreground "#c5c9c5"
set -gq @thm_datetime_icon_color "#8ba4b0"
set -gq @thm_session_icon_color "#c4746e"
set -gq @thm_element_background_default "#282727"
set -gq @thm_element_background_active "#8ba4b0"
set -gq @thm_element_background_bell "#282727"
set -gq @thm_bell_foreground "#c5c9c5"
set -gq @thm_bell_icon_color "#c4746e"
