set -gq @thm_background "#f2ecbc"
set -gq @thm_foreground "#43436c"
set -gq @thm_datetime_icon_color "#4d699b"
set -gq @thm_session_icon_color "#c84053"
set -gq @thm_element_background_default "#c7d7e0"
set -gq @thm_element_background_active "#4d699b"
set -gq @thm_element_background_bell "#c7d7e0"
set -gq @thm_bell_foreground "#43436c"
set -gq @thm_bell_icon_color "#c84053"
