set -g @thm_background "#1f1f28"
set -g @thm_foreground "#dcd7ba"
set -g @thm_element_background_default "#2a2a37"
set -g @thm_element_background_active "#2d4f67"
set -g @thm_datetime_icon_color "#7e9cd8"
set -g @thm_session_icon_color "#e6c384"
